force-app/main/default/objects/Scratch_Org_Creds__c/Scratch_Org_Creds__c.object-meta.xml
<CustomObject>
    <label>Scratch Org Creds</label>
    <nameField>
        <label>Scratch Org Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Creds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scratch_Org_Creds__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scratch_Org_Creds__c/fields/Org_Details__c.field-meta.xml
<CustomField>
    <fullName>Org_Details__c</fullName>
    <label>Org Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scratch_Org_Creds__c/fields/Req_ID__c.field-meta.xml
<CustomField>
    <fullName>Req_ID__c</fullName>
    <label>Req ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScratchOrgDetails.cls
public with sharing class ScratchOrgDetails {
    
    @AuraEnabled(cacheable=true)
    public static string getScratchOrgDetails() {
        string details;
        for(Scratch_Org_Creds__c oDetails : [Select id,Org_Details__c,Req_ID__c from Scratch_Org_Creds__c where name=:'ScratchOrgDetails' limit 1]){
            details = oDetails.Org_Details__c;
            break;
        }
        return details;
    }

    @AuraEnabled(cacheable=true)
    public static List<ScratchOrgDetails.sObjects> getOrgCountDetails() {
        string sOrgCount;
        for(Scratch_Org_Creds__c oDetails : [Select id,Org_Details__c,Data__c from Scratch_Org_Creds__c where name=:'ScratchOrgDetails' limit 1]){
            sOrgCount = oDetails.Data__c;
            break;
        }

        ScratchOrgDetails details =  (ScratchOrgDetails) System.JSON.deserialize(sOrgCount, ScratchOrgDetails.class);
        return details.sObjects;
    }

    // sorting is not working, need to work on this
    @AuraEnabled
    public List<SObjects> sObjects;

	public class SObjects implements Comparable{
        @AuraEnabled
		public Integer count;
        @AuraEnabled
		public String name;

        Public Integer compareTo(Object objToCompare) {
            return name.compareTo(((SObjects)objToCompare).name);            
	    }
	}

	
	

   
}